# Provision an S3 bucket for Synapse client integration tests.
# Tests can create storage locations in this bucket in order to
# verify custom external S3 location functionality.

# http://docs.synapse.org/articles/custom_storage_location.html
template_path: remote/s3-bucket.yaml
stack_name: synapse-dev-client-integration-test-bucket
parameters:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "jordan.kiangh@sagebase.org"
  AllowWriteBucket: 'true'

  BucketName: "synapse-dev-client-integration-test-external-s3"

  # data not sensitive, easier debugging
  EncryptBucket: 'false'

  # grants access to the synapse dev account as well as a programmatic IAM user
  GrantAccess:
    - 'arn:aws:iam::449435941126:root'
    - 'arn:aws:iam::449435941126:user/synapse-dev-client-integration-test-user'

  # data in this bucket is empheral, need only live for the duration of a test, can expire aggressively
  EnableDataLifeCycle: 'Enabled'
  LifecycleDataExpiration: '7'

# For CI system (do not change)
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/s3-bucket.yaml --create-dirs -o templates/remote/s3-bucket.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/s3-bucket.yaml --create-dirs -o templates/remote/s3-bucket.yaml"
  after_create:
    - !s3_notify "{{stack_group_config.aws_account_name}} {{stack_group_config.aws_account_email}}"
